### ISSUE TITLE
Black screen on arch

### ISSUE THREAD

**Issue by minystreem56** [r58Playz/terraos#10]
Most of this has been discused on discord but I'm putting it here as a lot of people are having that problem so it will need to be fixed I guss.

**Comment by GabeeCoding** [comment]
perhaps that kmscon tty thingy should be preinstalled/available as a build option with automatic setup @r58Playz

**Comment by r58Playz** [comment]
This is due to not updating systemd-chromiumos along with the rest of the system. I'll add this to the readme.
