### ISSUE TITLE
No Right Click For Trackpad Only On Chromebook

### ISSUE THREAD

**Issue by luhgarlicbread** [r58Playz/terraos#12]
I can't right click on Terraos Arch, board dedede. On ChromeOS I click with two fingers or ctrl+click and a right click will be registered. TerraOS Arch does not have these features. How could I get them?

**Comment by r58Playz** [comment]
You may have to enable 2-finger click. Check the touchpad settings or configure manually [via the Xorg configuration file](https://wiki.archlinux.org/title/libinput#Via_Xorg_configuration_file).

**Comment by luhgarlicbread** [comment]
I do not see that option in the settings. I can switch my mouse to the trackpad and that'll allow me to enable to tap it instead of fully click it to click. No right click, though.

**Comment by luhgarlicbread** [comment]
Ayeee I appreciate you btw :D

**Comment by luhgarlicbread** [comment]
Yo bruh right click works now with two fingers. How can I get it to work with ctrl+click? Is that possible?

**Comment by r58Playz** [comment]
> Yo bruh right click works now with two fingers. How can I get it to work with ctrl+click? Is that possible?

See [xbindkeys](https://wiki.archlinux.org/title/Xbindkeys).
