### ISSUE TITLE
Better boot menu

### ISSUE THREAD

**Issue by trevorwatkins1129** [r58Playz/terraos#13]
Instead of having a super complicated menu to navigate around (ok maybe its not that bad), it could be like old computers and have a "Press enter to interrupt startup..." screen, with a default boot partition.

**Comment by r58Playz** [comment]
Autoboot has been added to the docs, you can manually enable it

**Comment by trevorwatkins1129** [comment]
If I do enable auto boot, will I still be able to boot into an alternate partition if I want to without disabling it? Also can you describe in more detail how to enable it?
