### ISSUE TITLE
failed to enable kill-frecon service

### ISSUE THREAD

**Issue by sosdos** [r58Playz/terraos#14]
for some reason when I try to run the final script, after installing some packages w pacman I get "failed to enable kill-frecon service" along with some "target is busy" errors

**Comment by r58Playz** [comment]
Try rebooting, seems to fix it for me. No idea why it errors like that.

**Comment by sosdos** [comment]
nope, even after rebooting I get the exact same errors.

**Comment by sosdos** [comment]
for reference, this is the error(s).

perl: warning: Falling back to the standard locale ("C").
umount: /home/home/terraos/uwu/arch_rootfs/proc: target is busy.
umount: /home/home/terraos/uwu/arch_rootfs/dev: target is busy.
umount: /home/home/terraos/uwu/arch_rootfs/sys: target is busy.
umount: /home/home/terraos/uwu/arch_rootfs/proc: target is busy.
umount: /home/home/terraos/uwu/arch_rootfs/sys/firmware/efi/efivars: target is busy.
umount: /home/home/terraos/uwu/arch_rootfs/sys: target is busy.
New password: Retype new password: passwd: password updated successfully
umount: /home/home/terraos/uwu/arch_rootfs/proc: target is busy.
umount: /home/home/terraos/uwu/arch_rootfs/sys/firmware/efi/efivars: target is busy.
umount: /home/home/terraos/uwu/arch_rootfs/sys: target is busy.
umount: /home/home/terraos/uwu/arch_rootfs/sys: target is busy.
umount: /home/home/terraos/uwu/arch_rootfs/proc: target is busy.
Generating locales...
  en_US.UTF-8... done
Generation complete.
chroot: failed to run command ‘systemctl’: No such file or directory
umount: /home/home/terraos/uwu/arch_rootfs/proc: target is busy.
failed to enable kill-frecon service


ignore the fact that I named the build directory uwu lmao

**Comment by r58Playz** [comment]
Either your systemd-chromiumos package or your chroot was corrupted while installing. Nothing to fix on my side.

**Comment by sosdos** [comment]
alright well thanks anyways, I ended up just using an alreay built image and it works fine.
