### ISSUE TITLE
WPA3 / WPA2 Wi-Fi networks will not connect (excluding hotspots)

### ISSUE THREAD

**Issue by trevorwatkins1129** [r58Playz/terraos#17]

**Comment by r58Playz** [comment]
Please provide more info, like the logs of NetworkManager and wpa_supplicant.

**Comment by trevorwatkins1129** [comment]
I would but i have no idea how to access them. Can you provider instructions on how?

**Comment by zek-c** [comment]
my brother you dont know how to use system network services on linux and you expect to get this to work?? i think ubuntu would be better for you.

**Comment by trevorwatkins1129** [comment]
I use a different network manager on my main machine.

**Comment by r58Playz** [comment]
> I would but i have no idea how to access them. Can you provider instructions on how?

`journalctl -xeu NetworkManager` and `journalctl -xeu wpa_supplicant`
