### ISSUE TITLE
Terraos will not boot into any partion

### ISSUE THREAD

**Issue by Someguy224** [r58Playz/terraos#20]
Upon selecting the terra_arch option it gives returns error
(terraOs encountered an error.
backtrace: panicked at src/boot:29:10
Failed to mount partion: Custom kind Other, error: "Failed to excute process code some (255) stdout: '' stder: 'mount: mounting /dev/sda13 on /newroot failed:invalid argument/n'")
after that it closes the shell after 3 seconds
prebuilt image
board:octopus

**Comment by zek-c** [comment]
build it yourself, its most likely an issue with the prebuilts intended firmware/hardware.

**Comment by FunnyCheese4Me** [comment]
@Someguy224 where did you get the prebuilt image from?

**Comment by FunnyCorgi** [comment]
The dual chromeos and arch image is broken, arch won't boot. Here is a tutorial to fix that that I am following: https://github.com/3kh0/ext-remover/discussions/1085#discussioncomment-9657200

**Comment by Someguy224** [comment]
sorry i lost my acount for a while im back now ill try the fixes you suggested when i get time then ill close the issue

**Comment by Someguy224** [comment]
Got The Prebuilts From Here
https://files.mercurywork.shop/r58playz/terraos/

**Comment by Someguy224** [comment]
Everything works as expected
