### ISSUE TITLE
You must install "cpio" error

### ISSUE THREAD

**Issue by FunnyCorgi** [r58Playz/terraos#21]
When I run the build stage 1, I get an error.
Full terminal output starting at step 1:
@FunnyCorgi ➜ /workspaces/codespaces-blank $ git clone https://github.com/r58Playz/terraos.git
Cloning into 'terraos'...
remote: Enumerating objects: 347, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 347 (delta 38), reused 35 (delta 19), pack-reused 273
Receiving objects: 100% (347/347), 10.43 MiB | 28.55 MiB/s, done.
Resolving deltas: 100% (182/182), done.
@FunnyCorgi ➜ /workspaces/codespaces-blank $ cd terraos/
@FunnyCorgi ➜ /workspaces/codespaces-blank/terraos (rust-rewrite) $ mkdir build
@FunnyCorgi ➜ /workspaces/codespaces-blank/terraos (rust-rewrite) $ bash ../scripts/build_stage1.sh terraos
bash: ../scripts/build_stage1.sh: No such file or directory
@FunnyCorgi ➜ /workspaces/codespaces-blank/terraos (rust-rewrite) $ cd build
@FunnyCorgi ➜ /workspaces/codespaces-blank/terraos/build (rust-rewrite) $ bash ../scripts/build_stage1.sh terraos
Cloning into 'buildroot'...
remote: Enumerating objects: 476014, done.
remote: Total 476014 (delta 0), reused 0 (delta 0), pack-reused 476014
Receiving objects: 100% (476014/476014), 114.25 MiB | 31.28 MiB/s, done.
Resolving deltas: 100% (301175/301175), done.
mkdir -p /workspaces/codespaces-blank/terraos/build/buildroot/output/build/buildroot-config/lxdialog
PKG_CONFIG_PATH="" make CC="/usr/bin/gcc" HOSTCC="/usr/bin/gcc" \
    obj=/workspaces/codespaces-blank/terraos/build/buildroot/output/build/buildroot-config -C support/kconfig -f Makefile.br conf
make[1]: Entering directory '/workspaces/codespaces-blank/terraos/build/buildroot/support/kconfig'
/usr/bin/gcc -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DCURSES_LOC="<ncurses.h>" -DNCURSES_WIDECHAR=1 -DLOCALE  -I/workspaces/codespaces-blank/terraos/build/buildroot/output/build/buildroot-config -DCONFIG_=\"\"  -MM *.c > /workspaces/codespaces-blank/terraos/build/buildroot/output/build/buildroot-config/.depend 2>/dev/null || :
/usr/bin/gcc -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DCURSES_LOC="<ncurses.h>" -DNCURSES_WIDECHAR=1 -DLOCALE  -I/workspaces/codespaces-blank/terraos/build/buildroot/output/build/buildroot-config -DCONFIG_=\"\"   -c conf.c -o /workspaces/codespaces-blank/terraos/build/buildroot/output/build/buildroot-config/conf.o
/usr/bin/gcc -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DCURSES_LOC="<ncurses.h>" -DNCURSES_WIDECHAR=1 -DLOCALE  -I/workspaces/codespaces-blank/terraos/build/buildroot/output/build/buildroot-config -DCONFIG_=\"\"  -I. -c /workspaces/codespaces-blank/terraos/build/buildroot/output/build/buildroot-config/zconf.tab.c -o /workspaces/codespaces-blank/terraos/build/buildroot/output/build/buildroot-config/zconf.tab.o
/usr/bin/gcc -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DCURSES_LOC="<ncurses.h>" -DNCURSES_WIDECHAR=1 -DLOCALE  -I/workspaces/codespaces-blank/terraos/build/buildroot/output/build/buildroot-config -DCONFIG_=\"\"   /workspaces/codespaces-blank/terraos/build/buildroot/output/build/buildroot-config/conf.o /workspaces/codespaces-blank/terraos/build/buildroot/output/build/buildroot-config/zconf.tab.o  -o /workspaces/codespaces-blank/terraos/build/buildroot/output/build/buildroot-config/conf
rm /workspaces/codespaces-blank/terraos/build/buildroot/output/build/buildroot-config/zconf.tab.c
make[1]: Leaving directory '/workspaces/codespaces-blank/terraos/build/buildroot/support/kconfig'

configuration written to /workspaces/codespaces-blank/terraos/build/buildroot/.config

/usr/bin/make -j1  O=/workspaces/codespaces-blank/terraos/build/buildroot/output HOSTCC="/usr/bin/gcc" HOSTCXX="/usr/bin/g++" syncconfig
make[1]: Entering directory '/workspaces/codespaces-blank/terraos/build/buildroot'
make[1]: Leaving directory '/workspaces/codespaces-blank/terraos/build/buildroot'
You must install 'cpio' on your build machine
make: *** [support/dependencies/dependencies.mk:27: dependencies] Error 1
@FunnyCorgi ➜ /workspaces/codespaces-blank/terraos/build (rust-rewrite) $

**Comment by r58Playz** [comment]
Do what the error tells you; install `cpio`.

**Comment by FunnyCorgi** [comment]
I am getting this error:
@FunnyCorgi ➜ /workspaces/codespaces-blank/terraos/build (rust-rewrite) $ sudo apt install cpio
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package cpio is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  tar

E: Package 'cpio' has no installation candidate
