### ISSUE TITLE
Build aur not working

### ISSUE THREAD

**Issue by FunnyCorgi** [r58Playz/terraos#25]
gitpod /workspace/terraos/build (rust-rewrite) $ bash ../scripts/build_aur_packages.sh
Cloning into 'systemd-chromiumos'...
remote: Enumerating objects: 73, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 73 (delta 35), reused 43 (delta 13), pack-reused 0 (from 0)
Receiving objects: 100% (73/73), 80.15 KiB | 485.00 KiB/s, done.
Resolving deltas: 100% (35/35), done.
../scripts/build_aur_packages.sh: line 3: makepkg: command not found
cp: cannot stat '*.pkg.tar.zst': No such file or directory
fatal: destination path 'yay' already exists and is not an empty directory.
../scripts/build_aur_packages.sh: line 8: makepkg: command not found
cp: cannot stat '*.pkg.tar.zst': No such file or directory

**Comment by r58Playz** [comment]
Please use an Arch Linux system to build. Other distributions are not supported.

**Comment by FunnyCorgi** [comment]
What do you mean, "use an arch linux system to build."?

EDIT:I understand now oops.
