### ISSUE TITLE
Build stage 1 not working in arch linux

### ISSUE THREAD

**Issue by FunnyCheese4Me** [r58Playz/terraos#26]
You must install 'unzip' on your build machine
which: no rsync in (/vscode/bin/linux-x64/dc96b837cf6bb4af9cd736aa3af08cf8279f7685/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
You must install 'rsync' on your build machine
which: no bc in (/vscode/bin/linux-x64/dc96b837cf6bb4af9cd736aa3af08cf8279f7685/bin/remote-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
You must install 'bc' on your build machine
make: *** [support/dependencies/dependencies.mk:27: dependencies] Error 1
[root@codespaces-2c5b52 build]#

**Comment by r58Playz** [comment]
Do what it tells you. Install `unzip`, `rsync`, and `bc`.

**Comment by FunnyCheese4Me** [comment]
> Do what it tells you. Install `unzip`, `rsync`, and `bc`.

@r58Playz I don't know how to do that in arch

I am following online instructions for that, but it is saying I am not in the sudoers file(I created a user since you can't run makepkg as root)
