### ISSUE TITLE
lib kid compilation issue

### ISSUE THREAD

**Issue by happylabdab2** [r58Playz/terraos#32]
![Screenshot 2024-06-14 221518](https://github.com/r58Playz/terraos/assets/132798457/fe9208ff-dc92-4ff2-934c-0990c0bddc06)
What dependencies do i need to have to make it compile successfully?

OS: Ubuntu 22.04.4 LTS on Windows 10 x86_64
Kernel: 5.15.146.1-microsoft-standard-WSL2
Shell: bash 5.1.16

command
bash ./scripts/build_stage1.sh

Im on wsl btw

**Comment by r58Playz** [comment]
You must have `blkid` with its development files installed.

**Comment by happylabdab2** [comment]
Im trying it with libblkid-dev installed
and btw it would be helpfull if there was a dependency list

**Comment by happylabdab2** [comment]
Thank You, it works now

**Comment by happylabdab2** [comment]
For the people with same issue install the libblkid-dev package `sudo apt install libblkid-dev`
