### ISSUE TITLE
makepkg compilation issue

### ISSUE THREAD

**Issue by happylabdab2** [r58Playz/terraos#33]
I installed makepkg and it for some reason did not put a file in the systemd-chromiumos folder. How could i fix that? btw i installed from https://docs.google.com/open?id=0B7S255p3kFXNMS1hdEg3RzVpeEU using dpkg -i

`royan@GoogleNest:~/terraos/systemd-chromiumos$ sudo makepkg -s
WARNING: pkgtools are unstable with tar > 1.13.
         You should provide a "tar-1.13" in your $PATH.
dirname: invalid option -- 's'
Try 'dirname --help' for more information.
basename: option requires an argument -- 's'
Try 'basename --help' for more information.

Slackware package maker, version 3.14159.

Searching for symbolic links:

No symbolic links were found, so we won't make an installation script.
You can make your own later in ./install/doinst.sh and rebuild the
package if you like.

This next step is optional - you can set the directories in your package
to some sane permissions. If any of the directories in your package have
special permissions, then DO NOT reset them here!

Would you like to reset all directory permissions to 755 (drwxr-xr-x) and
directory ownerships to root.root ([y]es, [n]o)? n

Creating Slackware package:  /.tgz.tgz

./
./30-systemd-binfmt.hook
./0001-Use-Arch-Linux-device-access-groups.patch
./30-systemd-hwdb.hook
./20-systemd-sysusers.hook
./splash-arch.bmp
./.SRCINFO
./PKGBUILD
./keys/
./keys/pgp/
./keys/pgp/9A774DB5DB996C154EBBFBFDA0099A18E29326E1.asc
./keys/pgp/A9EA9081724FFAE0484C35A1A81CEA22BC8C7E2E.asc
./keys/pgp/63CDA1E5D3FC22B998D20DD6327F26951A015CC4.asc
./keys/pgp/5C251B5FC54EB2F80F407AAAC54CA336CFEB557E.asc
./30-systemd-update.hook
./0002-Disable-mount_nofollow-for-ChromiumOS-kernels.patch
./systemd.install
./arch.conf
./30-systemd-daemon-reload-system.hook
./loader.conf
./30-systemd-sysctl.hook
./systemd-hook
./systemd-user.pam
./30-systemd-udev-reload.hook
./30-systemd-catalog.hook
./.git/
./.git/index
./.git/config
./.git/branches/
./.git/packed-refs
./.git/hooks/
./.git/hooks/pre-commit.sample
./.git/hooks/post-update.sample
./.git/hooks/pre-receive.sample
./.git/hooks/pre-push.sample
./.git/hooks/pre-rebase.sample
./.git/hooks/prepare-commit-msg.sample
./.git/hooks/pre-merge-commit.sample
./.git/hooks/update.sample
./.git/hooks/applypatch-msg.sample
./.git/hooks/commit-msg.sample
./.git/hooks/push-to-checkout.sample
./.git/hooks/pre-applypatch.sample
./.git/hooks/fsmonitor-watchman.sample
./.git/refs/
./.git/refs/remotes/
./.git/refs/remotes/origin/
./.git/refs/remotes/origin/HEAD
./.git/refs/heads/
./.git/refs/heads/master
./.git/refs/tags/
./.git/logs/
./.git/logs/refs/
./.git/logs/refs/remotes/
./.git/logs/refs/remotes/origin/
./.git/logs/refs/remotes/origin/HEAD
./.git/logs/refs/heads/
./.git/logs/refs/heads/master
./.git/logs/HEAD
./.git/info/
./.git/info/exclude
./.git/objects/
./.git/objects/pack/
./.git/objects/pack/pack-47c4926649b82ac6287543040e3164544ce80594.pack
./.git/objects/pack/pack-47c4926649b82ac6287543040e3164544ce80594.idx
./.git/objects/info/
./.git/description
./.git/HEAD
./30-systemd-tmpfiles.hook
./30-systemd-daemon-reload-user.hook

Slackware package /.tgz.tgz created.

royan@GoogleNest:~/terraos/systemd-chromiumos$ ls
0001-Use-Arch-Linux-device-access-groups.patch            30-systemd-binfmt.hook                30-systemd-daemon-reload-user.hook  30-systemd-tmpfiles.hook     PKGBUILD   loader.conf      systemd-user.pam
0002-Disable-mount_nofollow-for-ChromiumOS-kernels.patch  30-systemd-catalog.hook               30-systemd-hwdb.hook                30-systemd-udev-reload.hook  arch.conf  splash-arch.bmp  systemd.install
20-systemd-sysusers.hook                                  30-systemd-daemon-reload-system.hook  30-systemd-sysctl.hook              30-systemd-update.hook       keys       systemd-hook
royan@GoogleNest:~/terraos/systemd-chromiumos$`

**Comment by r58Playz** [comment]
Please install Arch Linux's makepkg, not Slackware's makepkg.

**Comment by happylabdab2** [comment]
alrite

**Comment by happylabdab2** [comment]
how do i install it

**Comment by happylabdab2** [comment]
its now woking

**Comment by happylabdab2** [comment]
just switch to arch
