### ISSUE TITLE
Booting from squashfs not working?

### ISSUE THREAD

**Issue by Raf128** [r58Playz/terraos#35]
So i've decided to try booting from squashfs, an option in the boot menu of terraos. But after following the instructions very carefully, and navigating to the "Boot from squashfs" option, nothing appears it's just a screen with no directories. Here is info on the partition:
Size: 10.0 GB
Contents: FAT (32-bit version) Mounted at /media/user/PARTS
Partition Type: ChromeOS Root Filesystem

**Comment by r58Playz** [comment]
Where is your squashfs file (which partition, what path in the partition)?

**Comment by Raf128** [comment]
My squashfs file is in partition 5 which is the one mentioned above, and is in the root of said partition.

**Comment by r58Playz** [comment]
README:
> Place any squashfs files in the root of the first partition.

The boot from squashfs option only searches for squashfs files in the first partition (stateful partition).

**Comment by Raf128** [comment]
ok thank you

**Comment by ipushthecarts** [comment]
what counts as the 1st partitio? (1 2 3 or 4)
![Screenshot from 2024-09-07 18-38-19](https://github.com/user-attachments/assets/dc52c882-f3bf-44e9-b7c5-e53613105e66)

**Comment by gh-doot** [comment]
> what counts as the 1st partitio? (1 2 3 or 4) ![Screenshot from 2024-09-07 18-38-19](https://github.com/user-attachments/assets/dc52c882-f3bf-44e9-b7c5-e53613105e66)

1
